steps:
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
     gcloud config set project $PROJECT_ID
     echo "project property is changed"
     for i in $(ls -lrt ./modules/bigquery/views/* | awk '{print $9}')
     do
       sed -i -e s/\{PROJECT_ID\}/$PROJECT_ID/g $i
       sed -i -e s/\{ENV\}/${_ENV}/g $i
     done

     path=./module/bigquery/views/
     for i in $(cat ./module/bigquery/views/exe_master_ddl.parm)
           do
               echo "Processando o arquivo ->   " $i	
               echo "Arquivo em execução -> " $path$i
               bq query --use_legacy_sql=false " $(cat $path$i) "
               status=$?
               if [ $status == 0 ]
                 then echo "DDL Processado com éxito"
               else
                       echo "DDL falhou."
                       exit 1
               fi
           done    
options:
  logging:
    CLOUD_LOGGING_ONLY    
